import { Order, ShopSettings } from '../types/order';

export const DEFAULT_SETTINGS: ShopSettings = {
  shopName: 'MFA Bespoke Tailor',
  phone: '+66 2 123 4567',
  email: 'orders@mfatailor.com',
  address: 'Sukhumvit Soi 11, Bangkok, Thailand',
  currency: '฿',
  unit: 'in',
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1834',
    orderNumber: '1834',
    date: '2026-09-15',
    fittingStage: 2,
    status: 'fitting2',
    customer: {
      name: 'Alexander Wright',
      gender: 'male',
      hotel: 'The Landmark Bangkok',
      room: '1824',
      address: 'London, United Kingdom',
      phone: '+44 7911 123456',
      email: 'alex.wright@email.com',
    },
    items: [
      { id: '1', name: 'Suit', quantity: 1, price: 14500 },
      { id: '2', name: 'Shirt', quantity: 2, price: 1800 },
      { id: '3', name: 'Tie', quantity: 1, price: 600 },
    ],
    total: 18700,
    deposit: 9000,
    balance: 9700,
    shirt: {
      neck: '16.5',
      chest: '41',
      shoulderToChest: '10.5',
      bustSpan: '8.5',
      waist: '35',
      shoulderToWaist: '18',
      hips: '42',
      shoulders: '18.5',
      armRight: '25.5',
      armLeft: '25.5',
      frontChest: '17',
      back: '17.5',
      length: '31',
      shortSleeves: '10',
      notes: 'French cuff, spread collar, Italian cotton fabric',
    },
    pantSkirt: {
      waist: '34',
      hips: '41.5',
      crotch: '26',
      thigh: '25',
      length: '41',
      bottom: '15.5',
      notes: 'Flat front, side adjusters, no belt loops',
    },
    jacketCoatVest: {
      neck: '16.5',
      chest: '41.5',
      shoulderToChest: '11',
      bustSpan: '9',
      waist: '35.5',
      shoulderToWaist: '18.5',
      hips: '42',
      shoulders: '19',
      armRight: '25.5',
      armLeft: '25.5',
      frontChest: '17.5',
      back: '18',
      length: '30',
      notes: 'Peak lapel, 2-button, double vent, dark navy Super 130s wool',
    },
    specialRequest: 'Deliver to hotel reception before 5:00 PM on Friday. Prefers soft shoulder padding with hand-stitched pick lapels.',
    fabricNotes: 'Navy Italian Super 130s Wool (Roll #NV-884), White Egyptian Cotton for shirts',
    fittingDate: '2026-09-18',
    deliveryDate: '2026-09-20',
    createdAt: '2026-09-15T10:30:00Z',
    updatedAt: '2026-09-16T14:20:00Z',
  },
  {
    id: 'ord-1835',
    orderNumber: '1835',
    date: '2026-09-16',
    fittingStage: 1,
    status: 'fitting1',
    customer: {
      name: 'Sophia Laurent',
      gender: 'female',
      hotel: 'JW Marriott Sukhumvit',
      room: '1105',
      phone: '+33 6 12 34 56 78',
      email: 'sophia.laurent@paris.fr',
    },
    items: [
      { id: '1', name: 'Jacket', quantity: 1, price: 9500 },
      { id: '2', name: 'Skirt', quantity: 1, price: 3200 },
      { id: '3', name: 'Blouse', quantity: 2, price: 1900 },
    ],
    total: 16500,
    deposit: 8000,
    balance: 8500,
    shirt: {
      neck: '14.5',
      chest: '36',
      shoulderToChest: '9.5',
      bustSpan: '7.5',
      waist: '28',
      shoulderToWaist: '15.5',
      hips: '38',
      shoulders: '15.5',
      armRight: '23',
      armLeft: '23',
      frontChest: '14.5',
      back: '15',
      length: '26',
      notes: 'Silk crepe blouse, mother of pearl buttons',
    },
    pantSkirt: {
      waist: '27.5',
      hips: '38',
      crotch: '',
      thigh: '',
      length: '24',
      bottom: '',
      skirtLength: '24',
      notes: 'Pencil skirt, high waist, back slit 5 inches',
    },
    jacketCoatVest: {
      neck: '14.5',
      chest: '36.5',
      shoulderToChest: '10',
      bustSpan: '8',
      waist: '28.5',
      shoulderToWaist: '16',
      hips: '38.5',
      shoulders: '16',
      armRight: '23.5',
      armLeft: '23.5',
      frontChest: '15',
      back: '15.5',
      length: '25',
      notes: 'Single button tailored blazer, charcoal grey',
    },
    specialRequest: 'Wants extra hidden passport pocket inside the blazer lining. Skirt length must be strictly below knee.',
    fabricNotes: 'Charcoal Herringbone Wool & Ivory Silk Crepe',
    fittingDate: '2026-09-19',
    deliveryDate: '2026-09-22',
    createdAt: '2026-09-16T11:45:00Z',
    updatedAt: '2026-09-16T11:45:00Z',
  },
  {
    id: 'ord-1836',
    orderNumber: '1836',
    date: '2026-09-14',
    fittingStage: 3,
    status: 'finished',
    customer: {
      name: 'Michael Schmidt',
      gender: 'male',
      hotel: 'Hyatt Regency Bangkok',
      room: '2204',
      phone: '+49 170 9876543',
      email: 'm.schmidt@berlin-tech.de',
    },
    items: [
      { id: '1', name: 'Suit', quantity: 2, price: 13500 },
      { id: '2', name: 'Vest', quantity: 2, price: 3000 },
    ],
    total: 33000,
    deposit: 20000,
    balance: 13000,
    shirt: {},
    pantSkirt: {
      waist: '36',
      hips: '43',
      crotch: '27',
      thigh: '26',
      length: '42',
      bottom: '16',
    },
    jacketCoatVest: {
      chest: '43',
      waist: '37',
      hips: '43',
      shoulders: '19.5',
      armRight: '26',
      armLeft: '26',
      length: '31',
      vestLength: '24',
    },
    specialRequest: 'Include 2 extra fabric matching pocket squares and wooden hanger garment bags.',
    fabricNotes: '1x Dark Charcoal, 1x Midnight Blue 3-Piece Suits',
    fittingDate: '2026-09-16',
    deliveryDate: '2026-09-17',
    createdAt: '2026-09-14T09:15:00Z',
    updatedAt: '2026-09-16T16:00:00Z',
  },
];
